import 'package:firebase_database/firebase_database.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/chat_message_model.dart';

class GreenhouseChatService {
  static final GreenhouseChatService _instance =
      GreenhouseChatService._internal();
  final _firebaseDatabase = FirebaseDatabase.instance;
  final _firebaseAuth = FirebaseAuth.instance;

  factory GreenhouseChatService() {
    return _instance;
  }

  GreenhouseChatService._internal();

  /// Get the current user ID
  String? _getCurrentUserId() {
    return _firebaseAuth.currentUser?.uid;
  }

  /// Build the database reference path for a specific greenhouse
  DatabaseReference _getConversationsRef(String greenhouseId) {
    final uid = _getCurrentUserId();
    if (uid == null) throw Exception('User not authenticated');

    return _firebaseDatabase.ref(
      'users/$uid/greenhouses/$greenhouseId/chatbot/conversations',
    );
  }

  /// Save a new message to Firebase
  Future<String> saveMessage(
    String greenhouseId,
    String text,
    String sender,
  ) async {
    try {
      final conversationsRef = _getConversationsRef(greenhouseId);
      final message = ChatMessage(
        id: '', // ID will be generated by push()
        text: text,
        sender: sender,
        timestamp: DateTime.now(),
      );

      // Push creates a new child with an auto-generated key
      final newMessageRef = conversationsRef.push();
      await newMessageRef.set(message.toMap());

      return newMessageRef.key ?? '';
    } catch (e) {
      throw Exception('Failed to save message: $e');
    }
  }

  /// Get all messages for a greenhouse as a Stream (for real-time updates)
  Stream<List<ChatMessage>> getConversationsStream(String greenhouseId) {
    try {
      return _getConversationsRef(greenhouseId)
          .orderByChild('timestamp')
          .onValue
          .map((event) {
        final messages = <ChatMessage>[];
        if (event.snapshot.value != null) {
          final data = event.snapshot.value as Map<dynamic, dynamic>;
          data.forEach((key, value) {
            if (value is Map<dynamic, dynamic>) {
              final messageData = Map<String, dynamic>.from(value);
              final message = ChatMessage.fromMap(key.toString(), messageData);
              messages.add(message);
            }
          });
          // Sort by timestamp to ensure correct order
          messages.sort((a, b) => a.timestamp.compareTo(b.timestamp));
        }
        return messages;
      });
    } catch (e) {
      throw Exception('Failed to get conversations: $e');
    }
  }

  /// Get messages as a Future (for initial load)
  Future<List<ChatMessage>> getConversations(String greenhouseId) async {
    try {
      final snapshot = await _getConversationsRef(greenhouseId)
          .orderByChild('timestamp')
          .get();

      final messages = <ChatMessage>[];
      if (snapshot.value != null) {
        final data = snapshot.value as Map<dynamic, dynamic>;
        data.forEach((key, value) {
          if (value is Map<dynamic, dynamic>) {
            final messageData = Map<String, dynamic>.from(value);
            final message = ChatMessage.fromMap(key.toString(), messageData);
            messages.add(message);
          }
        });
        messages.sort((a, b) => a.timestamp.compareTo(b.timestamp));
      }
      return messages;
    } catch (e) {
      throw Exception('Failed to get conversations: $e');
    }
  }

  /// Delete a specific message
  Future<void> deleteMessage(String greenhouseId, String messageId) async {
    try {
      await _getConversationsRef(greenhouseId).child(messageId).remove();
    } catch (e) {
      throw Exception('Failed to delete message: $e');
    }
  }

  /// Clear all messages for a greenhouse
  Future<void> clearConversations(String greenhouseId) async {
    try {
      await _getConversationsRef(greenhouseId).remove();
    } catch (e) {
      throw Exception('Failed to clear conversations: $e');
    }
  }

  /// Get message count for a greenhouse
  Future<int> getMessageCount(String greenhouseId) async {
    try {
      final snapshot = await _getConversationsRef(greenhouseId).get();
      if (snapshot.value is Map) {
        final data = snapshot.value as Map<dynamic, dynamic>;
        return data.length;
      }
      return 0;
    } catch (e) {
      throw Exception('Failed to get message count: $e');
    }
  }
}
