// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn6qEFu9w6bkxp7zMc84B5zHtuz3iRZhY',
    appId: '1:544572974576:web:f1749ac41d653ae2c2e935',
    messagingSenderId: '544572974576',
    projectId: 'greenhouseapp-bd86f',
    authDomain: 'greenhouseapp-bd86f.firebaseapp.com',
    storageBucket: 'greenhouseapp-bd86f.firebasestorage.app',
    measurementId: 'G-HJS3EVL2HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKxbB18FefnvSQBR8uMRW6YMayKiLrVsI',
    appId: '1:544572974576:android:c9ff16a92a74972bc2e935',
    messagingSenderId: '544572974576',
    projectId: 'greenhouseapp-bd86f',
    storageBucket: 'greenhouseapp-bd86f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM_nJpIRyM5RSwhV4xTXCaJL9zdX_h4rg',
    appId: '1:544572974576:ios:e37ad0fc0d32a8a2c2e935',
    messagingSenderId: '544572974576',
    projectId: 'greenhouseapp-bd86f',
    storageBucket: 'greenhouseapp-bd86f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM_nJpIRyM5RSwhV4xTXCaJL9zdX_h4rg',
    appId: '1:544572974576:ios:e37ad0fc0d32a8a2c2e935',
    messagingSenderId: '544572974576',
    projectId: 'greenhouseapp-bd86f',
    storageBucket: 'greenhouseapp-bd86f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn6qEFu9w6bkxp7zMc84B5zHtuz3iRZhY',
    appId: '1:544572974576:web:55ba161e554919aac2e935',
    messagingSenderId: '544572974576',
    projectId: 'greenhouseapp-bd86f',
    authDomain: 'greenhouseapp-bd86f.firebaseapp.com',
    storageBucket: 'greenhouseapp-bd86f.firebasestorage.app',
    measurementId: 'G-FC8XJR8Z4J',
  );
}
